# Site settings
title: Dylan's Website 
email: ddibona@albany.edu
description: 11/11 Classwork
url: http://dibonad.github.io
github_username: DiBonaD

# Build settings
markdown: kramdown
permalink: pretty
